config/routes.rb
Rails.application.routes.draw do

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect { |p, request| request.flash[:error] = 'Authentication failure! ';
                                    'sessions/new' }

  delete 'signout', to: 'sessions#destroy', as: 'signout'

  post 'tweets/create'

  get 'sessions/new', to: 'sessions#new', as: 'signin'

  delete 'sessions/destroy'

  get 'home/show'

  root 'home#show'

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_attached_file(:tweet_picture)
  validates_attachment_content_type :tweet_picture, content_type: /\Aimage\/jpeg|png|gif\z/

  validates :user_id, presence: true
  validates :status, presence: true, length: {maximum: 140}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :signed_in_user

  def show
    @tweet = current_user.tweets.build
    @tweets = current_user.tweets.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new; end

  def create
    @user = TwitterApiService.find_or_create_from_omniauth(omniauth_hash)
    session[:user_id] = @user.id
    flash[:success] = 'You signed in!'
    redirect_to home_show_path
  end

  def destroy
    sign_out
    flash[:success] = 'You signed out from application'
    redirect_to signin_path
  end

  private

  def omniauth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :signed_in_user

  def create
    tweet_service = TweetService.new(current_user)
    if tweet_service.post_to_twitter(tweet_params)
      flash[:success] = 'You add the tweet'
      redirect_to root_path
    else
      @tweet = tweet_service.tweet
      respond_to do |format|
        format.html do
          @tweets = current_user.tweets.all
          render 'home/show'
        end
        format.js
      end
    end
  end

  private

  def tweet_params
    params.require(:tweet).permit(:status, :tweet_picture)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    user_id = session[:user_id]
    @current_user ||= User.find_by(id: user_id)
  end

  def current_user=(user)
    @current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    session.delete :user_id
    @current_user = nil
  end

  def signed_in_user
    redirect_to signin_path unless signed_in?
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/home/show.html.erb
<h1>Home page</h1>
<div class="container">
  <%= render 'tweets/new' %>
  <div class="tweets">
    <% @tweets.each do |tweet| %>
        <div class='tweet'>
          <%= render 'tweets/show', tweet: tweet %>
        </div>
    <% end %>
  </div>
</div>

app/views/layouts/_form_error_messages.html.erb
<% if object.errors.any? %>
    <div class="form_errors">
      The form contains <%= pluralize(object.errors.count, "error") %>.
      <ul>
        <% object.errors.full_messages.each do |message| %>
            <li>* <%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestTaskIkantam</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

<% if signed_in? %>
    <nav>
      <p>You signed in as <%= current_user.name %></p>
      <%= link_to 'Sign out', signout_path, method: :delete %>
    </nav>
<% end %>

<% flash.each do |key, value| %>
    <div class="alert-<%= key %>"><%= value %></div>
<% end %>
<%= yield %>
</body>
</html>

app/views/tweets/_new.html.erb
<%= form_for(@tweet, url: tweets_create_url, html: {multipart: true}, remote: true) do |f| %>
    <%= render 'layouts/form_error_messages', object: f.object %>
    <%= f.label :status %><br>
    <%= f.text_area :status %><br>
    <%= f.file_field :tweet_picture %><br>
    <%= f.submit 'Tweet!' %>
<% end %>

app/views/tweets/_show.html.erb
<p>
  <% if tweet.tweet_picture.file? %>
      <%= image_tag tweet.tweet_picture.url %>
  <% end %>
  <%= tweet.status %>
</p>
<p>
  <span>Posted <%= tweet.created_at.localtime.strftime "%d.%m.%Y %H:%M" %></span>
  <%= link_to 'View', tweet.tweet_url, target: '_blank' %>
</p>

app/views/tweets/create.js.erb
$('#new_tweet').html("<%= escape_javascript(render 'tweets/new')%>")